### ISSUE TITLE
Check out Anaconda

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/learning2code#1]
As per
https://twitter.com/kirstie_j/status/668739834664587264
and
https://www.continuum.io/why-anaconda
and
https://en.wikipedia.org/wiki/Anaconda_%28Python_distribution%29 .

**Comment by KirstieJane** [comment]
Wooo! Super strong support for this. The main plus point for me is that it makes updating and installing packages really easy. It also comes with the jupyter notebook already installed :)

Excited to follow your progress - have fun!

**Comment by Daniel-Mietchen** [comment]
I wanted to play around with IPython notebooks a bit, and at
http://ipython.org/install.html , they recommend installing via Anaconda, which I did. Went smooth. Now in the middle of [I have installed Anaconda; now what do I do?](http://docs.continuum.io/anaconda/faq#i-have-installed-anaconda-now-what-do-i-do).

**Comment by Daniel-Mietchen** [comment]
This actually went smoothly, so it's about time I close this ticket.
